blank_issues_enabled: false
contact_links:
  - name: Slack Community for Venafi Open Source Projects
    url: https://join.slack.com/t/venafi-integrations/shared_invite/zt-i8fwc379-kDJlmzU8OiIQOJFSwiA~dg
    about: Interact with other customers and the Venafi engineering and product teams
  - name: Security issues and general questions that can wait to be answered within a few days
    url: opensource@venafi.com
    about: Report security issues here
