blank_issues_enabled: false
contact_links:
  - name: Join us on Slack!
    url: https://join.slack.com/t/venafi-integrations/shared_invite/zt-i8fwc379-kDJlmzU8OiIQOJFSwiA~dg
    about: Interact with the Venafi team and customer community in real-time!
